version: '3.4'

services:
  booksapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DVTBooksDb=Server=mssql;Database=DVTBooksDev;User=sa;Password=P@ssw0rd
    ports:
      - 4201:80
  mssql:
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd
    volumes:
      - mssqldata:/var/opt/mssql
    ports:
      - 1433:1433

volumes:
  mssqldata:
